#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Process\Process;

define('SCRIPT', '/home/mike/dev/phpfarm/src/php-8.2.28/update-relay-dbs');

if ($argc < 2) {
    echo "Usage: {$argv[0]} <dbs>\n";
    exit(1);
} else if ($argv[1] < 1 || $argv[1] > 96) {
    echo "Error: <dbs> must be between 1 and 96.\n";
    exit(1);
}

$process = new Process(['ssh', 'hydra', SCRIPT, $argv[1]]);
if ($process->run() !== 0) {
    echo "Failed to execute " . SCRIPT . " on hydra\n";
    echo "Error: " . $process->getErrorOutput() . "\n";
    exit(1);
}
